### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by slyphix** [lazyguyy/TriggerMine#2]
I was so hyped for this game, I sold all of my belongings just to afford the in-app purchases. I am writing this from a filthy computer from the 90s at my local public library. Can I at least get a closed beta key?

**Comment by lazyguyy** [comment]
sorry to hear that you sold all your belongings, but what makes you assume you can buy this game for a measly $5? quality games take a lot of time to produce (as you probably do not know) and so I'm afraid it will take some more time until the product is finished. but don't worry -- if you're triggered because the development doesn't progress then I already achieved my goals.
In the meantime you could try activating this key on steam: GO04-NDFU-CKY0-URSL-FPLS :)
